export const apiUrl = {
  signupUrl: "api/user/register",
  getUser: "api/user/get-user",
  signIn: "api/user/login/",
  createdTenent: "api/user/create-tanent",
  getPriceingData: "api/public/subscription-package/",
  userSubscription: "api/user-subscription/",
  userGetSubscriptionPackage: "api/user-get/subscription-package/",
  userInvoice: "api/user-invoice/",
  SSO: "api/user/sso",

  superAdminPacakge: 'api/admin/subscription-package/',
  updateProfile: "api/user/admin-viewset/",
  getProfile: "api/user/user-profile/",
  superAdminPacakgeSetFeature: 'api/admin/feature/subscription-package/',
  generalSetting: 'api/general-setting/',
  heroSection: 'api/hero-section/',
  featureSection: 'api/feature-section/',
  sponsorSection: 'api/sponsor-section/',
  deliveryStepSection: 'api/delivery-step/section/',
  taskCountTtitleSection: 'api/task/count-title/section/',
  geSubscriptionData: "api/public/list/subscription-package",
  taskCountFeatureSection: 'api/task/count-feature/section/',
  testimonial: 'api/testimonial/',
  tenant: 'api/user/tenant/',
  tenantCount: 'api/user/tenant/count',
  invoice: 'api/invoice/',

  publicGeneralSetting: 'api/public/general-setting',
  publicHeroSection: 'api/public/hero-section',
  publicFeatureData: 'api/public/feature-section',
  publicSponsorData: 'api/public/sponsor-section',
  publicDeliveryData: 'api/public/delivery-step/section',
  publicTaskCountTitleSection: 'api/public/task/count-title/section',
  publicTaskCountFeatureSection: 'api/public/task/count-feature/section',
  publicTestimonial: 'api/public/testimonial',



};
